import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';

export async function createTestDatabase() {
	const db = new PGlite();
	await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;
 create table child_profiles(id bigint generated by default as identity primary key,name text,grade text,gender text,character_description text,story_themes text[],story_length_minutes integer);
 create table spelling_words(id bigint generated by default as identity primary key,word text,grade text,created_at timestamptz default now());
 create table spelling_attempts(id bigint generated by default as identity primary key,child_id bigint references child_profiles(id)on delete cascade,session_id text,word text,grade text,attempts_used integer,is_correct boolean,created_at timestamptz default now());
 grant all on all tables in schema public to service_role;grant usage on all sequences in schema public to service_role;
 insert into child_profiles(id,name,grade,gender)values(1,'Alex','1','boy'),(2,'Sam','K','girl');`);
	const files = (await fs.readdir('supabase/migrations'))
		.filter((f) => f.endsWith('_word_kitchen.sql'))
		.sort();
	for (const file of files) await db.exec(await fs.readFile(`supabase/migrations/${file}`, 'utf8'));
	return db;
}

if (process.argv[1]?.endsWith('test-db.mjs')) {
	const db = await createTestDatabase();
	const result = await db.query(
		`select tablename,rowsecurity from pg_tables where schemaname='public'and(tablename like 'game_%'or tablename like 'kitchen_%')`
	);
	assert(result.rows.length >= 20);
	assert(result.rows.every((r) => r.rowsecurity));
	for (const role of ['anon', 'authenticated']) {
		const grants = await db.query(
			`select has_table_privilege($1,'public.game_sessions','select') allowed, has_function_privilege($1,'public.wk_clear_history(bigint)','execute') rpc`,
			[role]
		);
		assert.equal(grants.rows[0].allowed, false);
		assert.equal(grants.rows[0].rpc, false);
	}
	console.log(
		`Migration applied to embedded PostgreSQL; ${result.rows.length} feature tables have RLS; client access and privileged RPC access are denied.`
	);
	await db.close();
}
